SET C51INC=D:\Program Files\Keil\C51\Inc;D:\Program Files\Keil\C51\Inc\Atmel
SET C51LIB=D:\Program Files\Keil\C51\Lib
SET CPU_TYPE=AT89S52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=samartAgr
SET CPU_XTAL=0x01F78A40
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\mysys.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\tasklist.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\AGREEM~1.__I"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\io.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\delay.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\uart.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\uart2.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\TFT_LCD.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\SIM800A.__i"
"D:\Program Files\Keil\C51\BIN\LX51.EXE" @".\Objects\SAMART~1.LNP"
"D:\Program Files\Keil\C51\BIN\OHX51.EXE" ".\Objects\samartAgr" HEX
